CREATE TABLE professores (
	id INT PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	cpf VARCHAR (11) UNIQUE
);

CREATE TABLE alunos (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	matricula VARCHAR(20) UNIQUE NOT NULL
);
